# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0005_alter_player_hometown'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbbgameespn',
            name='away_id',
            field=models.PositiveIntegerField(null=True, verbose_name='away team espn id'),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='away_points',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='home team total points'),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='favorite',
            field=models.CharField(max_length=64, null=True, verbose_name='vegas favorite'),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='home_id',
            field=models.PositiveIntegerField(null=True, verbose_name='home team espn id'),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='home_points',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='home team total points'),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espn_games', to='mbb.season'),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='spread',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mbbgameespn',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='combined point total'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='arena',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='favorite',
            field=models.CharField(max_length=64, null=True, verbose_name='vegas favorite'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='result',
            field=models.CharField(max_length=5, null=True, verbose_name='over/under result'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='score_one',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='score_two',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sref_games', to='mbb.season'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='spread',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='vegas spread'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='team_one_id',
            field=models.CharField(max_length=64, null=True, verbose_name='sref team one id'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='team_two_id',
            field=models.CharField(max_length=64, null=True, verbose_name='sref team one id'),
        ),
        migrations.AlterField(
            model_name='mbbgamesref',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='combined point total'),
        ),
    ]
