# Generated by Django 4.2.7 on 2023-11-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_mbbgameespn_away_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbbgameespn',
            name='arena',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
