# Generated by Django 4.2.7 on 2023-11-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_mbbgameespn_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbbstatlineespn',
            name='minutes',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='mbbstatlineespn',
            index=models.Index(fields=['game_code', 'player_id'], name='stats_mbbst_game_co_f6f444_idx'),
        ),
    ]
