# Generated by Django 4.2.7 on 2023-11-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_mbbstatlineespn_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbbstatlineespn',
            name='def_reb',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mbbstatlineespn',
            name='off_reb',
            field=models.SmallIntegerField(null=True),
        ),
    ]
