# Generated by Django 4.2.7 on 2023-11-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_mbbstatlineespn_def_reb_mbbstatlineespn_off_reb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbbgamesref',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='sref unique game id'),
        ),
    ]
