# Generated by Django 4.2.7 on 2023-11-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_mbbgamesref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbbstatlinesref',
            name='field_goal_pct',
        ),
        migrations.RemoveField(
            model_name='mbbstatlinesref',
            name='free_throw_pct',
        ),
        migrations.RemoveField(
            model_name='mbbstatlinesref',
            name='three_pt_pct',
        ),
        migrations.RemoveField(
            model_name='mbbstatlinesref',
            name='two_pt_pct',
        ),
        migrations.AddIndex(
            model_name='mbbstatlinesref',
            index=models.Index(fields=['game_code', 'player_id'], name='stats_mbbst_game_co_45fcc4_idx'),
        ),
    ]
