# Generated by Django 4.2.7 on 2023-11-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mascot',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
