# Generated by Django 4.2.7 on 2023-11-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0003_remove_team_school_espn_remove_team_school_sref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mbb.conference'),
        ),
    ]
