# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0004_alter_team_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hometown',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
