# Generated by Django 4.2.7 on 2023-11-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0005_alter_player_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='league_wins',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tag_line',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
