# Generated by Django 4.2.7 on 2023-12-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0007_alter_player_high_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='favorite',
            field=models.CharField(max_length=64, null=True, verbose_name='vegas favorite'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='spread',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='vegas point spread'),
        ),
        migrations.AlterField(
            model_name='game',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='vegas combined point total'),
        ),
    ]
