# Generated by Django 4.2.7 on 2023-12-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0008_alter_game_favorite_alter_game_location_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date', 'home_team', 'away_team'], name='mbb_game_date_ca8933_idx'),
        ),
    ]
