# Generated by Django 4.2.7 on 2023-12-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0009_game_mbb_game_date_ca8933_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='arena',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='espn_id',
            field=models.PositiveIntegerField(default=None, verbose_name='espn unique game id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='sref_id',
            field=models.CharField(default=None, max_length=64, verbose_name='sref unique game id'),
            preserve_default=False,
        ),
    ]
