# Generated by Django 4.2.7 on 2023-12-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbb', '0010_game_arena_game_espn_id_game_sref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statline',
            name='player_season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mbb.playerseason'),
            preserve_default=False,
        ),
    ]
